language: java
dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "macedoj-github"
    token:
      secure: SONAR_TOKEN

jdk:
  - openjdk11

before_script:
  - sleep 3
  - java --version

script:
  - ./gradlew clean build --stacktrace
  - sonar-scanner -Dsonar.verbose=true -X
