dist: trusty
sudo: required

language: java

addons:
  sonarcloud:
    organization: "macedoj-github"

jdk:
  - openjdk10

before_script:
  - sleep 5
  - java --version
  - gradle --version

script:
  - ./gradlew clean build --stacktrace
  - sonar-scanner
