language: java
dist: xenial
sudo: required

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "macedoj-github"
    token:
      secure: ${SONAR_TOKEN}

before_script:
  - sleep 3
  - java --version
  - ./gradlew --version

script:
  - ./gradlew clean build --stacktrace
  - ./gradlew jacocoTestReport
  - sonar-scanner -Dsonar.login=${SONAR_TOKEN} -Dsonar.verbose=true -X
#  - ./gradlew sonarqube \
#    -Dsonar.projectKey=macedoj_java-var-type-inference \
#    -Dsonar.organization=macedoj-github \
#    -Dsonar.host.url=https://sonarcloud.io \
#    -Dsonar.login=SONAR_TOKEN
