language: java
dist: trusty
sudo: required

jdk:
  - openjdk12

addons:
  sonarcloud:
    organization: "macedoj-github"
    token:
      secure: SONAR_TOKEN

before_script:
  - sleep 3
  - java --version

script:
  - ./gradlew clean build --stacktrace
  - ./gradlew jacocoTestReport
  - ./gradlew sonarqube \
    -Dsonar.projectKey=macedoj_java-var-type-inference \
    -Dsonar.organization=macedoj-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=SONAR_TOKEN
#  - sonar-scanner -Dsonar.verbose=true -X